on: [push]

jobs:
  test-sha256sum-action:
    runs-on: ubuntu-latest
    name: A job to test the sha256sum hashing
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sha256Sum Action 
        uses: ./ # Uses an action in the root directory
        id: hashing
        working-directory: ./test-data
        with:
          path-to-file: test.txt

      - name: verify hash
        run: cat ${{ steps.hashing.outputs.hash-file }}
     
